### PR TITLE
Fix the navigation menu not opening on touch

### PR DESCRIPTION
**Pull request by marek-lach**
Fixes the issue of the mobile menu not reacting to touch, in cases where mouse clicking is not being simulated.

### CODE REVIEW

**Comment by AnaGelez** [comment]
As you can see [here](https://circleci.com/gh/Plume-org/Plume/9186?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), `add_event_listener` only takes one argument in Rust.

However, I think replacing `|_: ClickEvent|` with `|_: TouchEnd|` may work.

**Comment by marek-lach** [comment]
The problem is that touchend is exclusive for iOS. Click event should still
probably stay for everything else...

**Comment by AnaGelez** [comment]
It seems to work on all mobile browsers: https://developer.mozilla.org/en-US/docs/Web/API/Document/touchend_event and we don't really care about desktop here I think, right?

**Comment by marek-lach** [comment]
Ok, I'll just modify it that way then...

**Comment by cybergipsy2020** [comment]
Hi I noticed that the menu button on the top left button still won't respond on ios browsers(safari and firefox). My plume is 0.4.0 and ios is 13.5.1.

**Comment by elegaanz** [comment]
I think Safari (and other browsers on iOS, which all use the same rendering engine, since Apple doesn't allow anything else in the AppStore) don't support WebAssembly. Maybe we should just switch back to pure JavaScript?

**Pull request merged**
