### PR TITLE
Update translation files

### PR DESCRIPTION
**Pull request by KitaitiMakoto**
so that translators can work on Crowdin.

### CODE REVIEW

**Comment by elegaanz** [comment]
I'm almost sure this is done automatically by our CI on every merge. Have you noticed a string that is in the code but not on Crowdin?

**Comment by KitaitiMakoto** [comment]
hmm, it's strange. For example, a phrase "Default theme" used at templates/{blogs,users}/edit.rs.html is not found on Crowdin.

I investigated a little. As you say, "push translations" job ran on CircleCI: https://circleci.com/gh/Plume-org/Plume/10322
But its log shows:

    #!/bin/bash -eo pipefail
    crowdin upload -b master
    
    Creating branch 'master' - SKIPPED
    File 'master/po/plume/plume.pot'- - SKIPPED
    File 'master/po/plume-front/plume-front.pot'\ - SKIPPED

It might be need to call `cargo build` before executing `crowdin upload`.

**Comment by elegaanz** [comment]
Could you try to add a `cargo build` at the beginning of this job, to see if it helps (ideally only for the master branch, so that a new PR doesn't push anything until it is merged)?

**Comment by KitaitiMakoto** [comment]
Okay, I created a new pull request: https://github.com/Plume-org/Plume/pull/748
Can you check it out after all checks are passed.

**Comment by KitaitiMakoto** [comment]
You see, #748 fixed the problem! thank you.

**Comment by elegaanz** [comment]
No, thank *you* for noticing and fixing it :wink:

**Pull request closed without merging**
