### PR TITLE
Fix some federation issue

### PR DESCRIPTION
**Pull request by fdb-hiroshima**
The issue in #567 will be a bit tougher than initially expected. Pterotype seems to use Organization instead of plain User for federation, so there is the question how do we manage that? How do we treat that? As users I expect, but it will require some changes to do so, or as something else?

### CODE REVIEW

**Comment by BaptisteGelez** [comment]
A post can't have an associated blog, but it technically can have no author. So I would say Organizations should be treated as blogs.

You can probably create a type that implements `AsActor` and the different `AsObject`, but that actually delegates the work to `Blog`? I don't know.

**Comment by fdb-hiroshima** [comment]
atm a post can't really have no authors : in multiple places assumption is made that there is at least one author, and we can use `posts.get_authors()?[0]` safely. There will be things to change if we introduce the possibility of a post without authors. Also as one can't follow a blog yet, this would mean a basic feature is lacking. The more I think about it, the more problematic it get

**Comment by BaptisteGelez** [comment]
OK, so then, what about inserting both a blog and an user with the same username when encountering an `Organization`? It is a bit hackish, but it should work.

Also, we should maybe add a "default" personnal blog for users at some, as I think it is what most people expect (but it may make the whole code a lot more complex too)?

**Comment by marek-lach** [comment]
For reference:

https://github.com/w3c/activitypub/issues/260

**Comment by marek-lach** [comment]
@fdb-hiroshima @BaptisteGelez According to the creator of _Pterotype_, `Organization` is the entire blog, not a specific user in the current design of the plugin.

I think this may help to shed some light on the issue at hand:
Screenshot 2019-05-16 at 17 12 46

**Comment by fdb-hiroshima** [comment]
this has been stall for too long. What has been fixed has been fixed, the rest will be at some point in the future

**Comment by AnaGelez** [comment]
Wait I just realized: do we fetch blogs with the `group:` prefix in Webfinger now?

**Comment by fdb-hiroshima** [comment]
```sh
$ curl 'https://pr-573.joinplu.me/.well-known/webfinger?resource=group:Test@pr-573.joinplu.me'
{
   "subject":"acct:Test@pr-573.joinplu.me",
   "aliases":[
      "https://pr-573.joinplu.me/~/Test/"
   ],
   "links":[
      {
         "rel":"http://webfinger.net/rel/profile-page",
         "href":"https://pr-573.joinplu.me/~/Test/"
      },
      {
         "rel":"http://schemas.google.com/g/2010#updates-from",
         "href":"https://pr-573.joinplu.me/~/Test/feed.atom",
         "type":"application/atom+xml"
      },
      {
         "rel":"self",
         "href":"https://pr-573.joinplu.me/~/Test/",
         "type":"application/activity+json"
      }
   ]
}
```

**Comment by fdb-hiroshima** [comment]
no, we don't 😬

**Pull request merged**
