### PR TITLE
Javascript for iOS

### LINKED ISSUE #842: Menu doesn't open on iOS
- **Plume version:** 0.6.1-dev
- **Operating system:** iOS
- **Web Browser:** Safari 

Reported at https://github.com/Plume-org/Plume/pull/838#issuecomment-762348815

### PR DESCRIPTION
**Pull request by marek-lach**
Without any CSS changes this time.

Complements #838, replaces #844, closes #842.

### CODE REVIEW

**Comment by iamdoubz** [comment]
So I did the following:

```cmd
git reset --hard
```

Removed extra files:

```cmd
rm -rf 3 844.patch assets/themes/default/_header.scss.rej js/ templates/base.rs.html.rej
```

Downloaded new patch `wget https://github.com/Plume-org/Plume/pull/845.patch`

Stat, check and apply patch (no errors!):

```cmd
git apply --stat 845.patch
git apply --check 845.patch
git apply 845.patch
```

Recompile Plume:

```cmd
cargo web deploy -p plume-front
cargo install --path plume-cli --force --features postgres
cargo install --path . --force --no-default-features --features postgres
plm migration run
```

Restart server:

```cmd
sudo service plume restart
```

### Results

- The patch creates a "js/" folder at root of Plume git folder.
- After recompile and server restart, I get two 404's saying https://hey.dou.bet/js/menu.js cannot be found.

I feel like the root js location is incorrect. Or, I need to add something to my apache2 reverse proxy to pick it up.

**Comment by iamdoubz** [comment]
So, I moved "menu.js" into the "static" folder along side "plume-front.js" and I changed the file `templates/base.rs.html` from

```html
<script src="/js/menus.js"></script>
```

To

```html
<script src="@uri!(plume_static_files: file = "menu.js", build_id = CACHE_NAME)"></script>
```

Recompiled, restarted and BOOM... it worked!!!

**Comment by marek-lach** [comment]
> So, I moved "menu.js" into the "static" folder along side "plume-front.js" and I changed the file `templates/base.rs.html` from
> 
> ```
> <script src="/js/menus.js"></script>
> ```
> 
> To
> 
> ```
> <script src="@uri!(plume_static_files: file = "menu.js", build_id = CACHE_NAME)"></script>
> ```
> 
> Recompiled, restarted and BOOM... it worked!!!
> 
> https://youtu.be/8dIK6zM2X5A

Yes, that works! I have just tested it also, can you submit it as a patch yourself?

**Comment by iamdoubz** [comment]
Here or at https://git.joinplu.me/ ?

**Comment by iamdoubz** [comment]
@marek-lach So, the static folder doesn't exist. So, we have to add  a patch to a directory that doesn't exist until after we compile. So, where in the "rust" code do we have to add this? Is it possible?

**Comment by marek-lach** [comment]
@iamdoubz I don't know nothing about Rust to be able to implement this, I think it would be best if @KitaitiMakoto implements it based on how you described it a few comments above.

**Comment by KitaitiMakoto** [comment]
Okay, I will take over.

**Pull request closed without merging**
