### PR TITLE
Run 'cargo fmt' to format code

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by Atul9** [comment]
Hi @BaptisteGelez I would like to add it. I am new to Plume project. Can you please point me to where in the .travis.yml file can `cargo fmt` be added?

**Comment by BaptisteGelez** [comment]
You can probably add a new item at the end of the `jobs` section, in the "test and coverage" stage (I'm not sure if this indication is clear enough, tell me if it is not :sweat_smile:)

**Comment by igalic** [comment]
given that the usual way to run `rustfmt` is in "check" mode, we can probably run it as first job. and from what i gather, `rustfmt` doesn't care about features, and just formats all code? or? did it format the test code, too?

**Comment by Atul9** [comment]
If the code isn't formatted ('rustfmt' will exit with 1 if there is an error in formatting - https://github.com/rust-lang/rustfmt#running) then is it still ok to go to the build stage?
Suggestion: We can add a `check` stage which will run before the build stage.
@BaptisteGelez @igalic What do you think?

**Comment by Atul9** [comment]
@BaptisteGelez @igalic I tried adding cargo fmt but the CI fails for weird reason.

I tried locally I didn't get this error - https://travis-ci.org/Plume-org/Plume/jobs/508992511#L584 & nor did it fail for the build before adding `cargo fmt` to travis.yml.

I tried to fix that but the build fails - https://travis-ci.org/Plume-org/Plume/jobs/509005663#L589

The build for this PR had passed before adding `cargo fmt` to travis build stages - https://travis-ci.org/Plume-org/Plume/builds/508519598

I suggest we can add `cargo fmt` to CI in another PR.

**Comment by BaptisteGelez** [comment]
OK, no problem. I'll merge this as soon as you'll have reverted the changes to `.travis.yml`. And thank you again for your work. :slightly_smiling_face:

**Comment by Atul9** [comment]
@BaptisteGelez done. I have updated the PR.

**Pull request merged**
