### PR TITLE
Confirm deletion of blog

### LINKED ISSUE #601: Confirmation before deleting a blog
**Is your feature request related to a problem? Please describe.**

The _Permanently delete this blog_ button is designed to look pretty dangerous, but clicking it just deletes the blog without any confirmation from the user.

This appears to occur even if the blog has posts associated with it.

**Describe the solution you'd like**

As a minimum, a JavaScript confirmation dialog similar to https://github.com/Plume-org/Plume/issues/184

**Describe alternatives you've considered**

Given the potential data loss associated with deleting a blog, an even more user-friendly approach might be to require the user to type the name of the blog to confirm it (similar to GitHub's delete repository feature)

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by rfwatson**
Closes #601.

~Ideally I'd like a less generic confirmation message - _Are you sure you want to permanently delete this blog?_. But assuming this won't be possible without new translations, I feel that it's probably not worth it. Thoughts welcome.~

### CODE REVIEW

**Comment by rfwatson** [comment]
Not sure why the CI is failing

**Comment by rfwatson** [comment]
Thanks!

Looking at the previous commits, would you recommend going on Crowdin directly to generate new translations? 

I’ll play with this further tomorrow.

**Comment by BaptisteGelez** [comment]
You don't need to go on Crowdin to add translations: any string written in the `i18n!` macro is uploaded there automatically, and can then be translated (once your PR is merged, of course).

**Comment by rfwatson** [comment]
> You don't need to go on Crowdin to add translations: any string written in the i18n! macro is uploaded there automatically

Oh nice :smiley: 

In that case I've updated this PR, and opened another to clarify the docs.

**Comment by BaptisteGelez** [comment]
Thank you again!

**Pull request merged**
