### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by BaptisteGelez**
Enjoy!

### CODE REVIEW

**Comment by BaptisteGelez** [comment]
OK… I guess I'll leave this PR open. :woman_shrugging:

**Comment by igalic** [comment]
can someone explain how this works, and why some of it is failing?

**Comment by fdb-hiroshima** [comment]
This is a bot committing translations from Crowdin via Bat's account, and all failing commits are actually builds that got canceled because a newer commit arrived before the build started processing

**Comment by marek-lach** [comment]
Looks like this would have to be rebuilt anew using Circle CI...

**Comment by BaptisteGelez** [comment]
For some reason the russian plural expression Crowdin generates can't be parsed by gettext. I'll try to debug this…

**Pull request merged**
