### PR TITLE
New design

### PR DESCRIPTION
**Pull request by Madeorsk**
+ New design!
+ Added link for author name in comments.
+ Added author full name in comments.
* Fixed label / input relation linking.

### CODE REVIEW

**Comment by m4sk1n** [comment]
screenshot
if anyone's curious how does it look

**Comment by stephenburgess8** [comment]
Hey, just wanted to say this looks great. I also wanted to echo Eliot and Baptiste on two points: line length and contrast. For line length, my go-to number is ~66 characters per line. That comes from **The Elements of Typographic Style** by Robert Bringhurst. He says comfortable reading line length is between 45 and 77 characters, with about 66 being ideal. The blog post above suggests 50-60, but I think you can get away with a little longer lines in long form posts.

The other thing is text contrast on background. I wrote a blog post about this including samples for minimum contrast. https://webdev.ink/2018/04/24/Text-Contrast-for-Web-Pages/ Basically, a 7:1 ratio of text to background color is the minimum to meet WCAG AAA standards and ensure that everyone can use the site easily. Looking forward to the next iteration!

**Comment by BaptisteGelez** [comment]
We plan to support theming, both for instances and blogs (see #40)

**Comment by BaptisteGelez** [comment]
Here are screenshots of the updated design for those who are curious:

capture d ecran de 2018-06-17 21-48-21

capture d ecran de 2018-06-17 21-48-44

**Comment by BaptisteGelez** [comment]
So, once again screenshots with the latest commits for those who don't want to install a development environment.

capture d ecran de 2018-06-19 22-41-58

(I personally love this new header :ok_hand:)

**Comment by BaptisteGelez** [comment]
@Madeorsk I don't know if you plan to make other changes to this branch but I'm okay to merge it as it is, even if some minor improvements could be made (it will never be too late to make them in other branches).

**Comment by m4sk1n** [comment]
This new header is great 😍

**Comment by Madeorsk** [comment]
I think you can merge!

Yes there is still a lot of things to do, like I said I want to change dashboard, followers list (we maybe need to add more informations than a name, same for the dashboard), like/reshare buttons and forms, at least.

**Comment by BaptisteGelez** [comment]
Thank you so much!

**Pull request merged**
