### PR TITLE
Basic CSS rules to keep content in iPhone X safe area

### PR DESCRIPTION
**Pull request by marek-lach**
This is just a small PR with _adds basic iPhone X support_ to the viewport tag and also adds CSS rules to forms for them to stay inside the iPhoxe X/R ''safe area'' space and not feel cut out.

safe-areas-webkit-ios

Other platforms and browsers are not affected by this change in any way, as all of these rules are only Apple specific.

It should achieve that no text, or form would be cut by the notch.

Right now article content on iPhone X is displayed like this:
Screenshot 2019-04-28 at 22 02 34

That is less than ideal. The PR works on resolving this issue.

### CODE REVIEW

**Comment by marek-lach** [comment]
Now this just just need some proper live testing to see if no element is out of place on any other platform. Unfortunately, I have no option to live-test at this point... Merging is not reccommended until full testing can be completed somehow.

**Comment by BaptisteGelez** [comment]
@marek-lach I rebased on master, which means it will be available on https://pr-554.joinplu.me as soon as the CI will be done.

**Comment by marek-lach** [comment]
Now this just just need some proper live testing to see if no element is out of place, or positioned oddly on any other platform. Unfortunately, I have no option to live-test at this point... Merging is not reccommended until full testing can be completed somehow.

**Comment by marek-lach** [comment]
> @marek-lach I rebased on master, which means it will be available on https://pr-554.joinplu.me as soon as the CI will be done.

Thanks.

**Comment by igalic** [comment]
i just get a 404 on that url

**Comment by BaptisteGelez** [comment]
Yes, the container on joinplu.me stopped for some reason. I will relaunch CI, and if it passes, the instance will be available again.

**Comment by BaptisteGelez** [comment]
So… the CI keeps failing for no reason, but hopefully it will get better once #558 will be merged. For the moment the test instances will probably remain unreachable…

**Comment by igalic** [comment]
or, @marek-lach could add something to the commit message, to [skip the ci](https://circleci.com/docs/2.0/skip-build/)

**Comment by fdb-hiroshima** [comment]
It wouldn't make in available on [plume-ci](http://pr-list.joinplu.me/) either

**Comment by marek-lach** [comment]
Hm.... I'll just simplify this pull request to include only basic fixes for webkit rendering, which would be safe to merge straight away and won't break anything. Then I can focus on circumventing the notch sometime later in a different PR when I get time...

**Pull request closed without merging**
