### PR TITLE
Fix menu animation not opening on iOS

### PR DESCRIPTION
**Pull request by marek-lach**
The menu does not open on iOS Safari because of how it can't handle `translateZ`, and needs an `-webkit` specific prefix for the `@keyframes` property for the animation to work. This PR fixes the issue.

### CODE REVIEW

**Comment by KitaitiMakoto** [comment]
Thanks! Can you fix indentation?

**Review by KitaitiMakoto — APPROVED** [review]

**Comment by KitaitiMakoto** [comment]
Tests passed! Ready to be merged?

**Comment by marek-lach** [comment]
> Tests passed! Ready to be merged?

Yes, all should be ok now.

**Review by KitaitiMakoto — APPROVED** [review]

**Comment by KitaitiMakoto** [comment]
Great! Thanks.

**Comment by iamdoubz** [comment]
Unfortunately, this still does not fix the menu opening on iOS. I am on version 0.6.1-dev [46fc030
](https://github.com/Plume-org/Plume/commit/46fc030df4e5d04541f620d7b5334dc1a5626b73).

**Comment by KitaitiMakoto** [comment]
Thanks for confirmation and reporting. We track that issue at #842

**Pull request merged**
